### PR TITLE
Add sessions sizes information before sessions table

### PR DESCRIPTION
**Pull request by aleksandr-m**

### CODE REVIEW

**Comment by evernat** [comment]
That's possible, yes.
What is the reason to do that change?

**Comment by aleksandr-m** [comment]
Finding myself scrolling to the bottom of the page to find that info.

**Comment by evernat** [comment]
ok, thanks

**Comment by evernat** [comment]
I have added a check to do that only when there are more than 20 sessions: ef42abf3905c12d0f51a09fbae8c36884b9b71d1

**Pull request merged**
