### PR TITLE
getThreadAllocatedBytes may get stuck when the system load is very high

### PR DESCRIPTION
**Pull request by lekko**
getThreadAllocatedBytes may get stuck when the system load is very high.
Set a timeout for thread memory invoke, then the catalina thread can got exception information.

support <jdk1.8, no lambda code

### CODE REVIEW

**Comment by evernat** [comment]
Please create an issue and describe the problem first. For example:
- Have you configured Spring to monitor some methods using MonitoringSpringInterceptor ? if yes, how/what kind of methods are monitored?
- And do you use the javamelody spring-boot-starter?
- Which version of javamelody are you using?
- Which version of java are you using?
- And to have a concrete understanding of the issue, can you make a screenshot of the twenty first lines of the detailed Spring statistics or whatever methods you monitor, for the week period, in the monitoring page? You can mask private information in the screenshot.

**Comment by evernat** [comment]
any news?

**Comment by lekko** [comment]
Sorry about the pending. 
I have used these code in my project for serveral days. And the exception doesn't come up again. Unfortunately, I didn't preserve the information, include screenshot or stack trace.
I have another project use javamelody too. I will updated my problem when got that exception again.

**Comment by evernat** [comment]
No news, so closing for now. Let us know if you have more information.

**Pull request closed without merging**
