### PR TITLE
introduce JPA naming strategy

### PR DESCRIPTION
**Pull request by HonoluluHenk**
See issue #563

### CODE REVIEW

**Comment by HonoluluHenk** [comment]
In case you merge this pull request or implement this feature in any other way, I'd be glad to further document this use case (source + Wiki) :)

**Comment by evernat** [comment]
This PR looks quite good, but:
1. Please change the header (copyright and licence) like for other javamelody files. It will be easier to read in English and it will allow me to change the licence if needed (for example to MIT).
2. I think that CriteriaWorkaroundLineNumbersJpa20NamingStrategy and CriteriaWorkaroundLineNumbersJpa21NamingStrategy should not be part of javamelody. You can create a new PR (to be closed) with these 2 files so that anyone can get them easily.
3. I think that javamelody parameters should be used instead of system property and ServiceLoader. That is add a value in the Parameter enum and use the Parameters.getParameter method. I can do that later if you wish.
4. Classes must be in the net.bull.javamelody package (and not .naming) like the other classes. I can also do that later if you wish.

And yes DefaultJpaNamingStrategy can replace the legacy naming strategy. I haven't seen differences which really change the behavior.

**Comment by HonoluluHenk** [comment]
Thanks for yor comments, I'll gladly implement all of them. 
I guess, I'll create a new guthub project for such workarounds (including those for hibernate you referenced in #563). 
Will also try to to some benchmarks to inform users about possible performance impacts. 

(not near a dev machine, so these changes might take some time)

Do you think the naming strategy pattern would be interesting for other parts (ejb,...) as well?

**Comment by evernat** [comment]
Great!
You can do that.

I do not think that the naming strategy would be really interesting for other parts, because getRequestName() can already be overrided in MonitoringFilter (http), MonitoringInterceptor and MonitoringTargetInterceptor (ejb), MonitoringSpringInterceptor, MonitoringGuiceInterceptor and can be customized in MonitoringProxy (services interfaces). And also there is not much too change in a sql request.

By the way, I would also prefer the name JpaDefaultNamingStrategy better than DefaultJpaNamingStrategy (for this class to be side by side with other Jpa*).

**Comment by HonoluluHenk** [comment]
Addendum for online documentation:
(At least) for JBoss 7/Wildfly, parameter configuration of "javamelody.jpa-naming-strategy" *must* be given as a system property on startup. Reason: everything JPA ist initialized *before* the servlet container and any parameter configuration in web.xml is therefore lost

**Pull request closed without merging**
