### PR TITLE
Add Prometheus metric collection support

### PR DESCRIPTION
**Pull request by slynn1324**
Adds a ?format=prometheus option to produce a report in the Prometheus text format, ready to be scraped by a Prometheus collection server. (https://prometheus.io/).

See comments in PrometheusController.java for a more detailed explanation.

### CODE REVIEW

**Comment by evernat** [comment]
Merged, many thanks.

And I have a few questions now:
1. Can you give a short text to include in the advanced user's guide about how to configure Promotheus? (for example, Click here, Enter url there and so on, perhaps with a screenshot.) You can see an example here:
https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#sending-metrics-to-graphite
2. It seems that an interval between data scrapings can be configured in Prometheus and the default interval seems to be 1m. What would you recommend for that interval for javamelody users in general? 1m? 
3. You say that there is an overhead of 5 - 10ms when enabling metrics of "last values", but is this overhead noticeable when there is already a http request to execute, once every 1m?
3. Would it be good to add metrics of type "counter" for cpu_millis and gc_millis (cpu and gc times used by the jvm since starting) and transactions count? I suppose that it will allow to have graphs of %cpu, %gc and transactions rate (count / sec) in Prometheus like in javamelody reports.
But if "last values" are enabled by default, you will have this graphs by default in Prometheus and in this case, we can also remove the redundant reportOnCollector method and so the calls to counter.getRequests() which can cost a bit when there are thousands of requests.

**Comment by evernat** [comment]
And I forgot, it would be great to know what javamelody metrics look like in Promotheus (many people including me don't know how it looks).

**Comment by slynn1324** [comment]
Thanks!  Here is a stab at answering your questions -- sorry it's quite a page full.  I've also attached a few screenshots of the Prometheus UI.  The Prometheus UI is pretty light and intended for checking queries and debugging - you would generally use Prometheus as a back-end for Grafana and create dashboards there.

Also, I'll shortly be submitting another PR to fix a couple of things here that I must have missed in backporting my changes over.  Apologies.

Let me know if you have more questions!  Thanks again for your great work on this project!


1 )   Here's a rough start at a section for the documentation

===================

**Exposing Metrics to Prometheus**

As an extra, since 1.70??, you can export metrics in a format that can be scraped by Prometheus (prometheus.io).  Prometheus differs from other collector integrations in that Prometheus is designed to scrape an available URL within services rather than receive them.  The metrics that are exposed by this report are real-time values of the JavaMelody counters, allowing the metrics resolution to be controlled by the Prometheus `scrape_interval` settings.  The metrics then can be visualized via the Prometheus web interface or in Grafana dashboards.

**"Last Value" metrics** 
Other collector integrations export the "lastValue" metrics that are commonly referred to as the "graphs" (the values that make up the graphs in the standard JavaMelody report).  These values are aggregated internally on a `javamelody.resolution-seconds` (default 60) window.  Prometheus generally prefers to ingest raw counters and real-time gauges when possible.  Because these metrics may be difficult to interpret correctly in Prometheus, and also many are redundant, they are disabled by default.  To enable, set the property `prometheus-include-last-value` to true in web.xml, in context or system properties like other parameters.  For example, in system properties set `javamelody.prometheus-include-last-value=true`.

To access the Prometheus formatted metrics, simply request `/monitoring?format=prometheus`. 

**Example scrape_config**
```
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any timeseries scraped from this config.
  - job_name: 'test_jm_app'

    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.
    #metrics_path: '/admin/monitoring'

    params:
      format: ['prometheus']

    static_configs:
      - targets: ['localhost:8080']
        labels:
          env: 'unit'
```

**Exported Metrics**
```
javamelody_memory_used_bytes
javamelody_memory_max_bytes
javamelody_memory_used_pct
javamelody_memory_perm_gen_used_bytes
javamelody_memory_perm_gen_max_bytes
javamelody_memory_perm_gen_used_pct
javamelody_sessions_active_count
javamelody_sessions_age_avg_minutes
javamelody_connections_used_count
javamelody_connections_max_count
javamelody_connections_active_count
javamelody_connections_used_pct
javamelody_system_load_avg
javamelody_system_cpu_load_pct
javamelody_system_unix_file_descriptors_open_count
javamelody_system_unix_file_descriptors_max
javamelody_system_unix_file_descriptors_open_pct
javamelody_system_processors_count
javamelody_system_tmp_space_free_bytes
javamelody_jvm_start_time
javamelody_threads_count
javamelody_threads_max_count
javamelody_threads_started_count
javamelody_threads_active_count
javamelody_job_executing_count
javamelody_tomcat_threads_max{tomcat_name="__name__"}
javamelody_tomcat_thread_busy_count{tomcat_name="__name__"}
javamelody_tomcat_received_bytes{tomcat_name="__name__"}
javamelody_tomcat_sent_bytes{tomcat_name="__name__"}
javamelody_tomcat_request_count{tomcat_name="__name__"}
javamelody_tomcat_error_count{tomcat_name="__name__"}
javamelody_tomcat_processing_time_millis{tomcat_name="__name__"}
javamelody_tomcat_max_time_millis{tomcat_name="__name__"}
javamelody_cache_in_memory_count{cache_name="__name__"}
javamelody_cache_in_memory_used_pct{cache_name="__name__"}
javamelody_cache_in_memory_hits_pct{cache_name="__name__"}
javamelody_cache_on_disk_count{cache_name="__name__"}
javamelody_cache_hits_pct{cache_name="__name__"}
javamelody_http_hits_count
javamelody_http_errors_count
javamelody_http_duration_millis
javamelody_sql_hits_count
javamelody_sql_errors_count
javamelody_sql_duration_millis
javamelody_jpa_hits_count
javamelody_jpa_errors_count
javamelody_jpa_duration_millis
javamelody_ejb_hits_count
javamelody_ejb_errors_count
javamelody_ejb_duration_millis
javamelody_spring_hits_count
javamelody_spring_errors_count
javamelody_spring_duration_millis
javamelody_guice_hits_count
javamelody_guice_errors_count
javamelody_guice_duration_millis
javamelody_services_hits_count
javamelody_services_errors_count
javamelody_services_duration_millis
javamelody_struts_hits_count
javamelody_struts_errors_count
javamelody_struts_duration_millis
javamelody_jsf_hits_count
javamelody_jsf_errors_count
javamelody_jsf_duration_millis
javamelody_jsp_hits_count
javamelody_jsp_errors_count
javamelody_jsp_duration_millis
javamelody_error_hits_count
javamelody_error_errors_count
javamelody_error_duration_millis
javamelody_log_hits_count
javamelody_log_errors_count
javamelody_log_duration_millis

# last value metrics -- disabled by default
javamelody_last_result_used_memory
javamelody_last_result_cpu
javamelody_last_result_http_sessions
javamelody_last_result_active_threads
javamelody_last_result_active_connections
javamelody_last_result_used_connections
javamelody_last_result_http_hits_rate
javamelody_last_result_http_mean_times
javamelody_last_result_http_system_errors
javamelody_last_result_sql_hits_rate
javamelody_last_result_sql_mean_times
javamelody_last_result_sql_system_errors
javamelody_last_result_spring_hits_rate
javamelody_last_result_spring_mean_times
javamelody_last_result_spring_system_errors
javamelody_last_result_gc
javamelody_last_result_thread_count
javamelody_last_result_loaded_classes_count
javamelody_last_result_used_buffered_memory
javamelody_last_result_used_non_heap_memory
javamelody_last_result_used_physical_memory_size
javamelody_last_result_used_swap_space_size
javamelody_last_result_system_load
javamelody_last_result_system_cpu_load
javamelody_last_result_file_descriptors
javamelody_last_result_http_sessions_mean_age
javamelody_last_result_transactions_rate
javamelody_last_result_free_disk_space
```

===================


2) Prometheus scrapes metrics from a collection urls for each system you want to gather metrics from, and the `scrape_interval` is configured within the Prometheus configuration. In their documentation, they state that the default is 1 minute, but the example configuration file that they distribute with the app sets it to 15 seconds.  My goal by exposing the real-time counter information is to allow the Prometheus configuration to define the resolution that  metrics are gathered based on it's `scrape_interval` setting.  The "best-practice" value probably greatly depends on what you're monitoring for, how much load your applications have, and how often you're comfortable haing the scrape requests execute.  Not sure there is a single answer here.

3) The comments about there being a 5-10ms overhead for the "last value" metrics is based on some rather primitive profiling that I did while exploring what was available in the JavaMelody internals.  I was observing ~8-13ms with the "last value" metrics enabled, less than 3ms with them disabled.  Those times are all internal execution times, network delivery not considered. Also, because the "last value" metrics are already aggregated over time in JavaMelody, they may be confusing and/or of little value.  I included them as optional in case users wanted them due to their familiarity with the existing "last value / graph" metrics.

4) cpu_millis and gc_millis would be great to add, but I didn't find them available in the internal APIs.  I just dug into the code yesterday, so apologies if I just missed them.  I'm not sure what you mean by "transaction count" -- http hits or sql transactions?  I am exposing http_hits and sql_hits (actually - hits, errors, and duration for each counter). If there is another meaningful raw counter that can be exposed - I'm all for it.

screen shot 2017-09-30 at 6 45 56 pm
screen shot 2017-09-30 at 5 34 21 pm

**Comment by evernat** [comment]
I have added cpu, gc, transactions and fixed NPE if no cache and also removed some values when undefined (c44a137)

**Comment by slynn1324** [comment]
Great - thanks!  I added one comment in the commit regarding the cpu percentage metric.

**Comment by slynn1324** [comment]
Thanks for all your work and responsiveness on this.  Do you have any idea of a timeframe that you are looking at a next release containing these changes?

**Comment by evernat** [comment]
The next release will be in about 1 month, 2 months maximum.

**Comment by evernat** [comment]
It is added now in the release notes and in the doc.
Thanks again.

**Comment by evernat** [comment]
To simplify javamelody parameters and usage from Prometheus, I have finally removed the `prometheus-include-last-value` javamelody parameter and replaced it by `includeLastValue` http parameter.

That is, change your scrape_config to:

```yml
    params:
      format: ['prometheus']
      includeLastValue: ['true']
```
See [doc](https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced).

Done in 08aacb2 for release 1.73

**Pull request merged**
