### PR TITLE
Too much sql error added by addRequestForSystemError method (#902)

### PR DESCRIPTION
**Pull request by mymilkbottles**
fix [902](https://github.com/javamelody/javamelody/issues/902)

### CODE REVIEW

**Comment by evernat** [comment]
First, the PR removes code from the addRequestsAndErrors method. That's not good because it was there for a good reason, which is aggregation of many different requests over a long period, such as a month or a year.

Then, what you have added is already done by the filterRequestsIfOverflow method in the Collector class, every 60 seconds by default. So I will ask questions in the related issue.

**Comment by mymilkbottles** [comment]
> First, the PR removes code from the addRequestsAndErrors method. That's not good because it was there for a good reason, which is aggregation of many different requests over a long period, such as a month or a year.
> 
> Then, what you have added is already done by the filterRequestsIfOverflow method in the Collector class, every 60 seconds by default. So I will ask questions in the related issue.

Thank you for your reply.
I think filterRequestsIfOverflow method remove overflow request every 60 seconds, it put some pressure on the application's memory.
javamelody as a lightweight monitor，should control memory cost every time.
so my  PR add ctlMaxRequestsCount method  to prevent too much memory cost in real time.

sorry i am very poor standard of English. QAQ

**Comment by mymilkbottles** [comment]
> First, the PR removes code from the addRequestsAndErrors method. That's not good because it was there for a good reason, which is aggregation of many different requests over a long period, such as a month or a year.
> 
> Then, what you have added is already done by the filterRequestsIfOverflow method in the Collector class, every 60 seconds by default. So I will ask questions in the related issue.

I also find a new exception that javamelody directory was create failed.
```
[] [javamelody] [WARN] [javamelody] [] [] [] [] [] [] - exception while collecting data: java.io.IOException: JavaMelody directory can't be created: /tmp/javamelody/_szpd-app
java.io.IOException: JavaMelody directory can't be created: /tmp/javamelody/_szpd-app
        at net.bull.javamelody.internal.model.JRobin.init(JRobin.java:186)
        at net.bull.javamelody.internal.model.JRobin.<init>(JRobin.java:123)
        at net.bull.javamelody.internal.model.JRobin.createInstance(JRobin.java:156)
        at net.bull.javamelody.internal.model.Collector.getCounterJRobin(Collector.java:911)
        at net.bull.javamelody.internal.model.Collector.collectJRobinValues(Collector.java:560)
        at net.bull.javamelody.internal.model.Collector.collectJavaInformations(Collector.java:422)
        at net.bull.javamelody.internal.model.Collector.collect(Collector.java:350)
        at net.bull.javamelody.internal.model.Collector.collectWithoutErrors(Collector.java:329)
        at net.bull.javamelody.internal.model.Collector.collectLocalContextWithoutErrors(Collector.java:318)
        at net.bull.javamelody.FilterContext$CollectTimerTask.run(FilterContext.java:81)
        at java.util.TimerThread.mainLoop(Timer.java:555)
        at java.util.TimerThread.run(Timer.java:505)
```
class Collector(net.bull.javamelody.internal.model.Collector ) job has too many work to do ,
any one of them throw exception will lead filterRequestsIfOverflow method unable to execute cause memory overflow. So i think my PR add ctlMaxRequestsCount method to prevent too much memory cost in real time , this is a good solution to avoid OOM.

**Comment by evernat** [comment]
I do not agree with your last comment but that's not the subject.
PR closed like #902.

**Pull request closed without merging**
