### PR TITLE
Fix some translations in resource bundle files

### PR DESCRIPTION
**Pull request by mawulf**

### CODE REVIEW

**Comment by evernat** [comment]
Thanks Marco

**Comment by evernat** [comment]
Hi Marco,
I have added two labels in resource bundle files,
https://github.com/javamelody/javamelody/commit/5029404eeb24e7b5c657453d06e9fc603fa5eb0d#diff-60eb43ef5f7f37cad9b7d8bdd3d80034 :
```
systemCpuLoad=% System CPU
usedBufferedMemory=Used buffered memory
```

If you want to improve those labels, you are welcome.
Emeric

**Comment by mawulf** [comment]
Hi evernat,
thanks for the invitation to help you with the translations.
See my pull request #507

**Comment by evernat** [comment]
Yes, it is merged now.
Thanks

**Pull request merged**
