### PR TITLE
add travisci and reportci

### PR DESCRIPTION
**Pull request by kortov**

### CODE REVIEW

**Comment by kortov** [comment]
I added a reportci via https://travis-ci.com/ (not .org) and https://report.ci/
it shows passed and failed tests like [this ](https://github.com/kortov/javamelody/pull/4/checks?check_run_id=363016900) 
later you can add badges like [here ](https://github.com/report-ci/junit-example)
to got it working you've got to login to beforementioned sites and add the project there

**Comment by evernat** [comment]
ok, thanks

**Comment by evernat** [comment]
Travis-ci & Report-ci seems to be granted in github.
Travis-ci seems ok: https://travis-ci.com/javamelody/javamelody/
Travis-ci check is ok but Report-ci check is not displayed on PR: https://github.com/javamelody/javamelody/pull/886/checks
The Report-ci check is only displayed at: https://github.com/javamelody/javamelody/runs/365600847

**Comment by kortov** [comment]
@evernat  I guess you should install this github app to see results https://github.com/marketplace/report-ci 
because I have it installed and it's working with PRs https://github.com/kortov/javamelody/pull/5

**Comment by evernat** [comment]
For some reason, a new PR 888 from a javamelody branch works much better. I have luck this time.
Travis CI and Report CI checks are displayed where expected. Previously existing checks (Codacy and Codeship with unit tests) have also run this time.

**Pull request merged**
