### PR TITLE
Spring Boot Starter for JavaMelody

### PR DESCRIPTION
**Pull request by georgwittberger**
I have created a first prototype of a Spring Boot starter package to facilitate the integration of JavaMelody in Spring Boot web applications.
Integration of JavaMelody is simplified to only having to add the starter dependency and use the provided configuration parameters in the "application.yml". See the subproject "javamelody-for-spring-boot" for an example.

### CODE REVIEW

**Comment by evernat** [comment]
Thanks for the PR.
First, a question: why adding the dependency aspectjweaver ? is it needed in general ? (it was not in the javamelody spring boot example)

Then some notes about things you can't know:
* application-type is not supposed to be configurable. It is supposed to be fixed, for example "Spring Boot".
* I think that the filter-name should not configurable, because 1) there is no reason for the user to configure it and 2) it is better if it is "javamelody" to override when needed the "javamelody" filter in the web-fragment.xml file inside javamelody.jar.
* I will probably not use "mvn release" for releases and deployment to repo.jenkins-ci.org is useless. So I think that we can remove distributionManagement and scm from pom.xml. And I am not sure either that inceptionYear, organization, issueManagement, ciManagement, and mailingList are really needed.
* I prefer to keep eclipse files in github (yes, I know it is often considered as bad practice).

**Comment by georgwittberger** [comment]
The reason for adding "aspectjweaver" to the starter POM was because of the instruction in the JavaMelody documentation: https://github.com/javamelody/javamelody/wiki/UserGuideAdvanced#spring-boot-app

I will check if it works without it since the "spring-boot-starter-web" may already include it transitively.

Regarding the other notes: I will submit an update today and try to make adjustments as needed.

* Remove application-type from configuration parameters.
* Remove filter-name from configuration parameters.
* Remove distributionManagement, inceptionYear, organization, issueManagement, ciManagement, and mailingList from the starter and example POMs (I took the core POM as a template, sorry).
* Re-add Eclipse project files (although I disagree with that, it's your repository, so you decide).

**Comment by georgwittberger** [comment]
Here we go. I have reworked the Spring Boot starter project respectively and also added the following:

* Unit test for the Spring Boot starter to test if auto-configuration works in a basic scenario
* Configuration parameter to allow definition of data sources to exclude from monitoring

One further note: The README.md of the starter project currently has the version number 1.64.0-SNAPSHOT hard-coded. You may have to make a little adjustment to the build process if you want to replace it with the release version automatically.

**Comment by georgwittberger** [comment]
Just added the documentation for another configuration parameter which allows to turn of monitoring for Spring services and controllers.

**Comment by evernat** [comment]
Good, it's great to have a javamelody spring-boot-starter.
I plan to publish that on Maven central.

**Pull request merged**
