### PR TITLE
Add ability to remove specific key from the cache

### PR DESCRIPTION
**Pull request by aleksandr-m**

### CODE REVIEW

**Comment by evernat** [comment]
Thanks for the PR.
But given that the number of cache keys may be quite high, the response time of cache.getKeys() may be high (8ms per 1000 keys according to javadoc) and the html page may be quite long in KB. And also the keys displayed in a small column may be difficult to read.

So I suggest that the cache keys are not displayed in the main html page. Instead, the cache details and the cache keys may be displayed in a separate table in a separate page for a single cache.
That is like the http session details with session attributes ; the code is [here](https://github.com/javamelody/javamelody/blob/master/javamelody-core/src/main/java/net/bull/javamelody/HtmlSessionInformationsReport.java#L271) except that there is sessionId instead of cacheId and SessionInformations instead of CacheInformations.
and you can see the sessions page in the [demo](http://javamelody.org/demo/monitoring?part=sessions).

**Comment by aleksandr-m** [comment]
Yes, it is even better. :) I'll see what I can do.

**Comment by aleksandr-m** [comment]
@evernat Please review. Not sure what should it be if `isFromCollectorServer` returns `true` in [`HtmlController`](https://github.com/javamelody/javamelody/pull/630/commits/5595bbbd9d5088d0cf4f8b2e45ee2e8d0e1d9ed6#diff-85b088e2cdf56edbc7b9eca853f770e2R321).

**Comment by evernat** [comment]
That's very good.
Just a few encoding that I will fix after and the collector server to fix.
Thanks!

**Comment by evernat** [comment]
Follow-up, I have pushed some fixes: the key was not removed when it is not a String, keys when in the collector server, ...
See d40ef9f4e614f76393c2671e6fc460e8e344475e

**Comment by aleksandr-m** [comment]
@evernat Thanks! One thing though - cache name can be an empty string. That is why I've created a separate keys column. Another possible solution is to replace empty name with some placeholder (e.g. `[blank_cache_name]`).

**Comment by evernat** [comment]
@aleksandr-m 
ok, I have fixed that (59caf6d9580c2bbe2b6a59ad434b788611b37ee8)

**Pull request merged**
