### PR TITLE
If enabled, expose counter request data via JMX

### PR DESCRIPTION
**Pull request by bapehbe**
Hello,

Thanks for the library, it has helped many times in production.

My company uses JMX extensively to monitor applications in production as well as javamelody. We thought it would be useful if javamelody could exposed data it gathers via JMX, so that we can, for example, set up alerts when global http time is much bigger than average.

Please review this pull request. My apologies for not writing Javadoc in French, I don't speak the language unfortunately.

Thanks

### CODE REVIEW

**Comment by evernat** [comment]
Sorry for the delay.
I am ok to expose JMX data. But can you add the header like for other classes?
Thanks.

**Comment by bapehbe** [comment]
Now it is my turn to apologize for the delay :)
I've added the headers, please have a look and let me know if there are any issues.
Thanks!

**Comment by evernat** [comment]
It's ok, thanks

**Comment by evernat** [comment]
Merged. I will probably refactor a bit.

**Comment by bapehbe** [comment]
Of course, thanks again for accepting the patch, much appreciated.

**Comment by evernat** [comment]
I have finished refactoring.
Here are some changes:
- parameter code renamed to jmx-expose-enabled
- getCpuTimeSum() and getDurationsSum() removed from CounterRequestData, because I don't think that they are useful (and note that durationsSum=hits x mean, cpuTimeSum=hits x cpuTimeMean)
- init moved to FilterContext class
- classes moved into CounterRequestMXBean
- new File(servletContext.getRealPath("/")).getName() replaced by Parameters.getContextPath(Parameters.getServletContext()) because directory may not always exist or be reliable (this may change your mbeans names)

**Comment by evernat** [comment]
Note: in order to not open a jmx connection each time you want to get a value, you can call a http request to get the value as text.
For example:
http://localhost:8080/yourwebapp/monitoring?jmxValue=net.bull.javamelody:type=CounterRequest,context=yourwebapp,name=http.CounterRequestAggregation

And you can look at the [ExternalAPI](https://github.com/javamelody/javamelody/wiki/ExternalAPI) to get other data, such as last values in charts.
For example:
http://localhost:8080/yourwebapp/monitoring?part=lastValue&graph=usedMemory

**Pull request merged**
